metricbeat.modules:
  - module: elasticsearch
    xpack.enabled: true
    period: 10s
    hosts: ["https://es01:9200","https://es02:9200","https://es03:9200"]
    ssl.enabled: true
    ssl.certificate_authorities: "/usr/share/metricbeat/certs/ca/ca.crt"
    username: ${ELASTIC_USER}
    password: ${ELASTIC_PASSWORD}

  - module: kibana
    xpack.enabled: true
    metricsets:
      - stats
    period: 10s
    hosts: ${KIBANA_HOSTS}
    username: ${ELASTIC_USER}
    password: ${ELASTIC_PASSWORD}

  # - module: system
  #   period: 10s
  #   hosts: ["localhost"]
  #   cpu.metrics: [percentages]
  #   process.include_top_n:
  #     enabled: true
  #     by_cpu: 5
  #     by_memory: 5

  - module: docker
    metricsets:
      - container
      - cpu
      - diskio
      - healthcheck
      - info
      - memory
      - network
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enabled: true

processors:
  - add_host_metadata: {}
  - add_docker_metadata: {}

# Opcional: que Metricbeat pueda cargar assets en Kibana (dashboards, etc.)
setup.kibana:
  host: ${KIBANA_HOSTS}

output.elasticsearch:
  hosts: ["https://es01:9200","https://es02:9200","https://es03:9200"]
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl:
    certificate_authorities: "/usr/share/metricbeat/certs/ca/ca.crt"
    verification_mode: full